services:
    ai-bot:
        build:
            context: .
            dockerfile: Dockerfile
        image: ai-bot:latest
        pull_policy: never
        container_name: ai-bot
        restart: unless-stopped
        networks:
            - flowise-network
        environment:
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - NVIDIA_API_KEY=${NVIDIA_API_KEY}
            - FLOWISE_URL=${FLOWISE_URL}
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 2G

networks:
  flowise-network:
    external: true
