services:
    ai-bot:
        build:
            context: .
            dockerfile: Dockerfile
        image: ai-bot:0.1.0
        pull_policy: never
        container_name: ai-bot
        restart: unless-stopped
        environment:
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - NVIDIA_API_KEY=${NVIDIA_API_KEY}
            - FLOWISE_URL=${FLOWISE_URL}
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 2G
